---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: emqtt-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: emqtt
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""

---

apiVersion: v1
kind: Service
metadata:
  name: ekka
  namespace: emqtt

  labels:
    app: ekka
spec:
  type: NodePort
  ports:
    - port: 1883
      nodePort: 30001
      protocol: TCP
      name: mqtt
    - port: 8883
      nodePort: 30002
      protocol: TCP
      name: mqttssl
    - port: 8080
      nodePort: 30003
      protocol: TCP
      name: mgmt
    - port: 18083
      nodePort: 30004
      protocol: TCP
      name: dashboard
    - port: 4369
      nodePort: 30005
      protocol: TCP
      name: mapping
    - port: 8083
      nodePort: 30006
      protocol: TCP
      name: ws
    - port: 8084
      nodePort: 30007
      protocol: TCP
      name: wss
  selector:
    app: ekka

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ekka
  namespace: emqtt
spec:
  replicas: 1
  serviceName: ekka
  template:
    metadata:
      labels: 
        app: ekka
    spec:
      securityContext:
        fsGroup: 0
        runAsUser: 0
      containers:
      - name: ekka
        image: qomputer/one:v1
        imagePullPolicy: Always
        volumeMounts:
        - name: data-storage
          mountPath: /home/maxim/server/Mnesia.ekka@127.0.0.1
        ports:
          - containerPort: 1883
          - containerPort: 8883
          - containerPort: 8080
          - containerPort: 8083
          - containerPort: 8084
          - containerPort: 18083
          - containerPort: 8888
          - containerPort: 4369
        readinessProbe:
          tcpSocket:
            port: 1883
          initialDelaySeconds: 30
          periodSeconds: 40
        env:
          - name: EMQ_NAME
            value: "ekka"
          - name: EMQ_CLUSTER__DISCOVERY
            value: "k8s"
          - name: EMQ_CLUSTER__K8S__APISERVER
            value: "https://kubernetes.default:443"
          - name: EMQ_CLUSTER__K8S__NAMESPACE
            value: "emqtt"
          - name: EMQ_CLUSTER__K8S__SERVICE_NAME
            value: "ekka"
          - name: EMQ_CLUSTER__K8S__ADDRESS_TYPE
            value: "ip"
          - name: EMQ_CLUSTER__K8S__APP_NAME
            value: "ekka"
          - name: EMQ_CLUSTER__NAME
            value: "emqcl"
          - name: EMQ_CLUSTER__AUTOHEAL
            value: "on"
          - name: EMQ_CLUSTER__AUTOCLEAN
            value: "5m"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash", "-c", "/home/maxim/server/halt_save.sh"]
      volumes:
        - name: data-storage
          persistentVolumeClaim:
            claimName: data-pv-claim
