apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  storageClassName: "standart"
  hostPath:
    path: /home/maxim/server/Mnesia.synrc@127.0.0.1/
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pv-claim
spec:
  volumeName: pv0001
  storageClassName: "standart"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
